// enemies.js
// Canonical catalog of bespoke enemy movement traits.
//
// Each entry describes locomotion, physics, and hitbox overrides that do not
// cleanly fit into weapon or level configuration. The definitions are kept in a
// standalone file so systems that need to reason about enemy movement (AI,
// collision, dev tools) can share a single source of truth without reaching
// into level scripts.

const ENEMY_TRAITS = Object.freeze({
  baldRoller: Object.freeze({
    speedMult: 1,
    moveSpeed: 184,
    moveForce: 5200,
    airMoveForce: 3800,
    moveDecel: 3400,
    jumpSpeed: 300,
    maxFallSpeed: 720,
    hitboxWidth: 68,
    hitboxHeight: 64,
    hitboxOffsetY: -6,
    physicsType: 'nonStick',
    locomotion: 'roller',
    floats: false,
    flies: false
  }),
  slimeCube: Object.freeze({
    speedMult: 1,
    moveSpeed: 136,
    moveForce: 4000,
    airMoveForce: 2600,
    moveDecel: 4200,
    jumpSpeed: 360,
    maxFallSpeed: 680,
    hitboxWidth: 72,
    hitboxHeight: 52,
    hitboxOffsetY: -10,
    physicsType: 'nonStick',
    locomotion: 'hopper',
    floats: false,
    flies: false
  }),
  tripodSpinner: Object.freeze({
    speedMult: 1,
    moveSpeed: 166,
    moveForce: 5000,
    airMoveForce: 3600,
    moveDecel: 3600,
    jumpSpeed: 310,
    maxFallSpeed: 680,
    hitboxWidth: 66,
    hitboxHeight: 84,
    hitboxOffsetY: -6,
    physicsType: 'nonStick',
    locomotion: 'tripod',
    floats: false,
    flies: false
  }),
  psiSkyRanger: Object.freeze({
    speedMult: 1,
    moveSpeed: 176,
    moveForce: 5000,
    airMoveForce: 3600,
    moveDecel: 3400,
    jumpSpeed: 320,
    maxFallSpeed: 720,
    hitboxWidth: 60,
    hitboxHeight: 112,
    hitboxOffsetY: -6,
    physicsType: 'stick',
    locomotion: 'acrobatic',
    floats: false,
    flies: false
  }),
  glyphGyre: Object.freeze({
    speedMult: 1,
    moveSpeed: 120,
    moveForce: 2800,
    airMoveForce: 2800,
    moveDecel: 2000,
    jumpSpeed: 280,
    maxFallSpeed: 600,
    hitboxWidth: 96,
    hitboxHeight: 96,
    hitboxOffsetY: 0,
    hitboxShape: 'ellipse',
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  timeWraith: Object.freeze({
    speedMult: 1,
    moveSpeed: 80,
    moveForce: 2600,
    airMoveForce: 2600,
    moveDecel: 2600,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 68,
    hitboxHeight: 68,
    hitboxOffsetY: 0,
    orbRadius: 34,
    hitboxShape: 'ellipse',
    passThroughTerrain: true,
    ghost: true,
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  realmGuardian: Object.freeze({
    speedMult: 1,
    moveSpeed: 70,
    moveForce: 0,
    airMoveForce: 0,
    moveDecel: 4800,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 263.5,
    hitboxHeight: 340.5,
    hitboxOffsetY: 15,
    passThroughTerrain: true,
    ghost: true,
    physicsType: 'nonStick',
    locomotion: 'sentinel',
    floats: true,
    flies: true
  }),
  tricylicSlasher: Object.freeze({
    speedMult: 1,
    moveSpeed: 0,
    moveForce: 0,
    airMoveForce: 0,
    moveDecel: 0,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 92,
    hitboxHeight: 92,
    hitboxOffsetY: 0,
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  sandBlock: Object.freeze({
    speedMult: 1,
    moveSpeed: 118,
    moveForce: 3600,
    airMoveForce: 1600,
    moveDecel: 4000,
    jumpSpeed: 320,
    maxFallSpeed: 660,
    hitboxWidth: 112,
    hitboxHeight: 96,
    hitboxOffsetY: 0,
    physicsType: 'nonStick',
    locomotion: 'block',
    floats: false,
    flies: false
  }),
  sandWanderer: Object.freeze({
    speedMult: 1,
    moveSpeed: 146,
    moveForce: 4200,
    airMoveForce: 3200,
    moveDecel: 3600,
    jumpSpeed: 340,
    maxFallSpeed: 700,
    hitboxWidth: 88,
    hitboxHeight: 120,
    hitboxOffsetY: -4,
    physicsType: 'nonStick',
    locomotion: 'sandShade',
    floats: false,
    flies: false
  }),
  alephGlyph: Object.freeze({
    speedMult: 1,
    moveSpeed: 110,
    moveForce: 2600,
    airMoveForce: 2600,
    moveDecel: 2400,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 88,
    hitboxHeight: 120,
    hitboxOffsetY: -12,
    hitboxShape: 'ellipse',
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  shinGlyph: Object.freeze({
    speedMult: 1,
    moveSpeed: 140,
    moveForce: 3200,
    airMoveForce: 3200,
    moveDecel: 2200,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 48,
    hitboxHeight: 62,
    hitboxOffsetY: -8,
    hitboxShape: 'ellipse',
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  zetaGlyph: Object.freeze({
    speedMult: 1,
    moveSpeed: 126,
    moveForce: 3200,
    airMoveForce: 3200,
    moveDecel: 2400,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 108,
    hitboxHeight: 112,
    hitboxOffsetY: -10,
    hitboxShape: 'ellipse',
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  xiGlyph: Object.freeze({
    speedMult: 1,
    moveSpeed: 132,
    moveForce: 3400,
    airMoveForce: 3400,
    moveDecel: 2500,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 108,
    hitboxHeight: 112,
    hitboxOffsetY: -10,
    hitboxShape: 'ellipse',
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: true,
    flies: true
  }),
  thetaHarmonic: Object.freeze({
    speedMult: 0,
    moveSpeed: 0,
    moveForce: 0,
    airMoveForce: 0,
    moveDecel: 0,
    jumpSpeed: 0,
    maxFallSpeed: 0,
    hitboxWidth: 148,
    hitboxHeight: 148,
    hitboxOffsetY: 0,
    hitboxShape: 'ellipse',
    physicsType: 'nonStick',
    locomotion: 'hover',
    floats: false,
    flies: false
  })
});

function getEnemyTrait(kind){
  if(!kind) return null;
  const trait = ENEMY_TRAITS[kind];
  if(!trait || typeof trait !== 'object') return null;
  return Object.assign({}, trait);
}
